New version
Fixed some rules
Made the rules use the new build system
LSB'ed init

diff --git a/resources/debian/app.init.d.in b/resources/debian/app.init.d.in
--- a/resources/debian/app.init.d.in
+++ b/resources/debian/app.init.d.in
@@ -6,6 +6,16 @@
 # Copyright 2010, @NAME@
 #
 
+### BEGIN INIT INFO
+# Provides: @APP@-@CLUSTER@
+# Required-Start: $local_fs $network $named
+# Required-Stop: $local_fs $network $named
+# Default-Start:  2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: start and stop @APP@-@CLUSTER@
+# Description: @APP@-@CLUSTER@ application
+### END INIT INFO
+
 APP=@APP@
 USER=@USER@
 CLUSTER=@CLUSTER@
@@ -31,6 +41,8 @@ export PLAY_PID_PATH=$PLAY_PID_FOLDER/$APP.pid
 export PLAY_LOG_PATH=/var/log/$APP_FOLDER
 DESC="$APP_NAME application"
 
+. /lib/lsb/init-functions
+
 if test -f /etc/default/$APP_NAME
 then
 	. /etc/default/$APP_NAME
@@ -40,7 +52,7 @@ test -d $APP_PATH || exit 0
 
 if test "$IS_PLAY_CONFIGURED" = 0
 then
-	echo "You must configure $APP_NAME in /etc/default/$APP_NAME before running it"
+	log_failure_msg "You must configure $APP_NAME in /etc/default/$APP_NAME before running it"
 	case "$1" in
     	stop)
     	exit 0
@@ -68,39 +80,58 @@ set -e
 
 case "$1" in
     start)
-        echo -n "Starting $DESC: "
+        log_daemon_msg "Starting $DESC" $APP
 
-	if start-stop-daemon --start --pidfile $PLAY_PID_PATH --user $USER --chuid $USER:$USER --quiet --exec $PLAY -- start $APP_PATH $PLAY_ARGS > /dev/null
-	then
-		echo "done."
-	else
-		echo "failed (already running?)."
-		exit 1
-	fi
-    ;;
+		if start-stop-daemon --start --pidfile $PLAY_PID_PATH --user $USER --chuid $USER:$USER --quiet --exec $PLAY -- start $APP_PATH $PLAY_ARGS > /dev/null
+		then
+			log_end_msg 0
+		else
+			log_failure_msg "failed (already running?)."
+			log_end_msg 1
+			exit 1
+		fi
+	;;
 
     stop)
-        echo -n "Stopping $DESC: "
-
-	if start-stop-daemon --stop --oknodo --pidfile $PLAY_PID_PATH --user $USER --chuid $USER:$USER --quiet --retry 5
-	then
-		test -f $PLAY_PID_PATH && rm $PLAY_PID_PATH
-	    echo "done."
-	else
-		echo "failed (not running?)."
-	fi
-    ;;
+		log_daemon_msg "Stopping $DESC" vcs-play
+		if start-stop-daemon --stop --oknodo --pidfile $PLAY_PID_PATH --user $USER --chuid $USER:$USER --quiet --retry 5
+		then
+			test -f $PLAY_PID_PATH && rm $PLAY_PID_PATH
+			log_end_msg 0
+		else
+			log_failure_msg "failed (not running?)."
+			log_end_msg 1
+			exit 1
+		fi
+	;;
 
     restart|force-reload)
         $0 stop
         $0 start
     ;;
 
+    status)
+	if test -f $PLAY_PID_PATH
+	then
+		PID=$(cat $PLAY_PID_PATH)
+		if (grep '(java)' /proc/$PID/stat && grep play /proc/$PID/cmdline) > /dev/null
+		then
+			log_success_msg "$DESC is running"
+			exit 0
+		else
+			log_success_msg "$DESC is not running"
+			exit 3
+		fi
+	else
+		log_success_msg "$DESC is not running"
+		exit 3
+	fi
+    ;;
+
     *)
-        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
+        log_action_msg "Usage: $0 {start|stop|restart|force-reload|status}" >&2
         exit 1
     ;;
 esac
 
 exit 0
-
